name: secureme
description: SecureMe - Aplikasi Perlindungan dan Pelaporan Kekerasan

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.3.0
  go_router: ^13.0.0
  flutter_svg: ^2.0.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/